### ISSUE TITLE
5.2.5版本，point断开重连，分配的ip地址无法及时释放

### ISSUE THREAD

**Issue by myzzzqqwa** [danieldin95/openlan-go#31]
![image](https://user-images.githubusercontent.com/24540630/84349846-c2f8be80-abea-11ea-8ae6-549d8b94a7ab.png)

**Comment by danieldin95** [comment]
确认下是udp环境？

**Comment by myzzzqqwa** [comment]
kcp环境

**Comment by danieldin95** [comment]
添加两种机制1.point优雅离开；2.udp超时检测。
