### ISSUE TITLE
配置文件中的network目录怎么用的？

### ISSUE THREAD

**Issue by mynicolas** [danieldin95/openlan-go#33]

**Comment by mynicolas** [comment]
point端需要手动写路由，需要改进一下，像openvpn一样，服务端配置好需要的路由，客户端自动注入路由

**Comment by danieldin95** [comment]
服务端可以配置路由，要看你用的那个版本？

**Comment by danieldin95** [comment]
每个版本都有个/etc下都有个example，你可以参考下

**Comment by mynicolas** [comment]
我用的是4.3.16，按照example的配置，客户端并没有自动配置路由，能不能有个各个字段的配置详解?

**Comment by danieldin95** [comment]
首先确认你的网络配置json格式正确，客户端如果需要下发路由请不要再配置地址，服务端会分配地址和下发路由。

**Comment by mynicolas** [comment]
如果仍然需要客户端保持ip不变，该怎么做呢？

**Comment by danieldin95** [comment]
windows可以在网卡上配置静态地址，linux配置{"interface": "bridge": "xxx"}， 在网桥上配置静态地址。

**Comment by mynicolas** [comment]
也就是说，如果需要注入路由，静态ip就不能配置point的配置文件里了

**Comment by danieldin95** [comment]
是的。地址租约机制还没开发。

**Comment by danieldin95** [comment]
5.2.18版本计划支持主机地址分配

**Comment by danieldin95** [comment]
咱们这边使用openlan主要用来做什么业务？

**Comment by mynicolas** [comment]
主要是测试，之前用的是openvpn，拿你这个对比一下，openvpn支持客户端固定ip

**Comment by danieldin95** [comment]
5.2.18已经release了，支持静态地址分配，详细参考network.json.example.

**Comment by mynicolas** [comment]
高效
